{
 "title": "sre-demo-api",
 "tags": [
  "sre-demo-api",
  "observabilidade"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Disponibilidade do Serviço",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "http_server_up" }
   ]
  },
  {
   "title": "Total de Requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_requests_total)" }
   ]
  },
  {
   "title": "Taxa de Erros (req/s)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code!=\"200\"}[5m]))"
    }
   ]
  },
  {
   "title": "Requisições por Segundo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Volume de Requisições por Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total[5m])",
     "legendFormat": "{{method}} {{endpoint}} [{{status_code}}]"
    }
   ]
  },
  {
   "title": "Requisições por Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status_code) (rate(http_requests_total[5m]))",
     "legendFormat": "HTTP {{status_code}}"
    }
   ]
  },
  {
   "title": "Goroutines Ativas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{job=\"sre-demo-api\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"sre-demo-api\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"sre-demo-api\"}",
     "legendFormat": "Heap Alloc"
    }
   ]
  }
 ]
}